# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AgenceAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertDate', models.DateTimeField()),
                ('fixedDate', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('agenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Agence')),
            ],
        ),
        migrations.CreateModel(
            name='AgenceUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Agence')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('chef_only', models.CharField(default='yes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('matricule', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('is_chef', models.CharField(default='yes', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='agenceusers',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Users'),
        ),
        migrations.AddField(
            model_name='agencealerts',
            name='alertID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Alerts'),
        ),
        migrations.AddField(
            model_name='agencealerts',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Users'),
        ),
    ]
