# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTN', '0002_auto_20210812_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='city',
            field=models.CharField(default='tunis', max_length=150),
            preserve_default=False,
        ),
    ]
