# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-26 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostTN', '0004_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='work_area',
            field=models.CharField(default='Tunis', max_length=50),
            preserve_default=False,
        ),
    ]
