# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostTN', '0005_users_work_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('agenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Agence')),
                ('systemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostTN.Systems')),
            ],
        ),
    ]
