# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostTN', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='systemID',
        ),
        migrations.AddField(
            model_name='notification',
            name='alertID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PostTN.Alerts'),
            preserve_default=False,
        ),
    ]
